set -e

# Testes do guião
test/compare_simpledu_du.sh "./simpledu" "-l test/test-folder"
test/compare_simpledu_du.sh "./simpledu" "-l test/test-folder -b"
test/compare_simpledu_du.sh "./simpledu" "-l test/test-folder -b -S"
test/compare_simpledu_du.sh "./simpledu" "-l test/test-folder -b -S --max-depth=2"
test/compare_simpledu_du.sh "./simpledu" "-l test/test-folder -B 1"
test/compare_simpledu_du.sh "./simpledu" "-l test/test-folder -a"
test/compare_simpledu_du.sh "./simpledu" "-l test/test-folder -a -L"

# Testes '-l'
test/compare_simpledu_du.sh "./simpledu" "-l test/test-folder"
test/compare_simpledu_du.sh "./simpledu" "-l ."
test/compare_simpledu_du.sh "./simpledu" "-l include"
test/compare_simpledu_du.sh "./simpledu" "-l acutest"
test/compare_simpledu_du.sh "./simpledu" "--count-links test/test-folder"
test/compare_simpledu_du.sh "./simpledu" "--count-links ."
test/compare_simpledu_du.sh "./simpledu" "--count-links include"
test/compare_simpledu_du.sh "./simpledu" "--count-links acutest"

# Testes '-a'
test/compare_simpledu_du.sh "./simpledu" "-l -a test/test-folder"
test/compare_simpledu_du.sh "./simpledu" "-l -a ."
test/compare_simpledu_du.sh "./simpledu" "-l -a include"
test/compare_simpledu_du.sh "./simpledu" "-l -a acutest"
test/compare_simpledu_du.sh "./simpledu" "-l --all test/test-folder"
test/compare_simpledu_du.sh "./simpledu" "-l --all ."
test/compare_simpledu_du.sh "./simpledu" "-l --all include"
test/compare_simpledu_du.sh "./simpledu" "-l --all acutest"

# Testes '-b'
test/compare_simpledu_du.sh "./simpledu" "-l -b test/test-folder"
test/compare_simpledu_du.sh "./simpledu" "-l -b ."
test/compare_simpledu_du.sh "./simpledu" "-l -b include"
test/compare_simpledu_du.sh "./simpledu" "-l -b acutest"
test/compare_simpledu_du.sh "./simpledu" "-l --bytes test/test-folder"
test/compare_simpledu_du.sh "./simpledu" "-l --bytes ."
test/compare_simpledu_du.sh "./simpledu" "-l --bytes include"
test/compare_simpledu_du.sh "./simpledu" "-l --bytes acutest"

# Testes '-B'
test/compare_simpledu_du.sh "./simpledu" "-l -B 1 test/test-folder"
test/compare_simpledu_du.sh "./simpledu" "-l -B 1 ."
test/compare_simpledu_du.sh "./simpledu" "-l -B 1 include"
test/compare_simpledu_du.sh "./simpledu" "-l -B 1 acutest"
test/compare_simpledu_du.sh "./simpledu" "-l -B 3 test/test-folder"
test/compare_simpledu_du.sh "./simpledu" "-l -B 3 ."
test/compare_simpledu_du.sh "./simpledu" "-l -B 3 include"
test/compare_simpledu_du.sh "./simpledu" "-l -B 3 acutest"
test/compare_simpledu_du.sh "./simpledu" "-l -B 8 test/test-folder"
test/compare_simpledu_du.sh "./simpledu" "-l -B 8 ."
test/compare_simpledu_du.sh "./simpledu" "-l -B 8 include"
test/compare_simpledu_du.sh "./simpledu" "-l -B 8 acutest"
test/compare_simpledu_du.sh "./simpledu" "-l -B 1000 test/test-folder"
test/compare_simpledu_du.sh "./simpledu" "-l -B 1000 ."
test/compare_simpledu_du.sh "./simpledu" "-l -B 1000 include"
test/compare_simpledu_du.sh "./simpledu" "-l -B 1000 acutest"
test/compare_simpledu_du.sh "./simpledu" "-l -B 1025 test/test-folder"
test/compare_simpledu_du.sh "./simpledu" "-l -B 1025 ."
test/compare_simpledu_du.sh "./simpledu" "-l -B 1025 include"
test/compare_simpledu_du.sh "./simpledu" "-l -B 1025 acutest"

test/compare_simpledu_du.sh "./simpledu" "-l --block-size 1 test/test-folder"
test/compare_simpledu_du.sh "./simpledu" "-l --block-size 1 ."
test/compare_simpledu_du.sh "./simpledu" "-l --block-size 1 include"
test/compare_simpledu_du.sh "./simpledu" "-l --block-size 1 acutest"
test/compare_simpledu_du.sh "./simpledu" "-l --block-size 3 test/test-folder"
test/compare_simpledu_du.sh "./simpledu" "-l --block-size 3 ."
test/compare_simpledu_du.sh "./simpledu" "-l --block-size 3 include"
test/compare_simpledu_du.sh "./simpledu" "-l --block-size 3 acutest"
test/compare_simpledu_du.sh "./simpledu" "-l --block-size 8 test/test-folder"
test/compare_simpledu_du.sh "./simpledu" "-l --block-size 8 ."
test/compare_simpledu_du.sh "./simpledu" "-l --block-size 8 include"
test/compare_simpledu_du.sh "./simpledu" "-l --block-size 8 acutest"
test/compare_simpledu_du.sh "./simpledu" "-l --block-size 1000 test/test-folder"
test/compare_simpledu_du.sh "./simpledu" "-l --block-size 1000 ."
test/compare_simpledu_du.sh "./simpledu" "-l --block-size 1000 include"
test/compare_simpledu_du.sh "./simpledu" "-l --block-size 1000 acutest"
test/compare_simpledu_du.sh "./simpledu" "-l --block-size 1025 test/test-folder"
test/compare_simpledu_du.sh "./simpledu" "-l --block-size 1025 ."
test/compare_simpledu_du.sh "./simpledu" "-l --block-size 1025 include"
test/compare_simpledu_du.sh "./simpledu" "-l --block-size 1025 acutest"

test/compare_simpledu_du.sh "./simpledu" "-l --block-size=1 test/test-folder"
test/compare_simpledu_du.sh "./simpledu" "-l --block-size=1 ."
test/compare_simpledu_du.sh "./simpledu" "-l --block-size=1 include"
test/compare_simpledu_du.sh "./simpledu" "-l --block-size=1 acutest"
test/compare_simpledu_du.sh "./simpledu" "-l --block-size=3 test/test-folder"
test/compare_simpledu_du.sh "./simpledu" "-l --block-size=3 ."
test/compare_simpledu_du.sh "./simpledu" "-l --block-size=3 include"
test/compare_simpledu_du.sh "./simpledu" "-l --block-size=3 acutest"
test/compare_simpledu_du.sh "./simpledu" "-l --block-size=8 test/test-folder"
test/compare_simpledu_du.sh "./simpledu" "-l --block-size=8 ."
test/compare_simpledu_du.sh "./simpledu" "-l --block-size=8 include"
test/compare_simpledu_du.sh "./simpledu" "-l --block-size=8 acutest"
test/compare_simpledu_du.sh "./simpledu" "-l --block-size=1000 test/test-folder"
test/compare_simpledu_du.sh "./simpledu" "-l --block-size=1000 ."
test/compare_simpledu_du.sh "./simpledu" "-l --block-size=1000 include"
test/compare_simpledu_du.sh "./simpledu" "-l --block-size=1000 acutest"
test/compare_simpledu_du.sh "./simpledu" "-l --block-size=1025 test/test-folder"
test/compare_simpledu_du.sh "./simpledu" "-l --block-size=1025 ."
test/compare_simpledu_du.sh "./simpledu" "-l --block-size=1025 include"
test/compare_simpledu_du.sh "./simpledu" "-l --block-size=1025 acutest"

# Testes '-L'
test/compare_simpledu_du.sh "./simpledu" "-l test/test-folder/D2"
test/compare_simpledu_du.sh "./simpledu" "-l test/test-folder/D1/Db/Dx"
test/compare_simpledu_du.sh "./simpledu" "-l test/test-folder"
test/compare_simpledu_du.sh "./simpledu" "-l test/test-folder/D1/Db/Dx/symlnk"

test/compare_simpledu_du.sh "./simpledu" "-l -L test/test-folder"
test/compare_simpledu_du.sh "./simpledu" "-l -L ."
test/compare_simpledu_du.sh "./simpledu" "-l -L include"
test/compare_simpledu_du.sh "./simpledu" "-l -L acutest"
test/compare_simpledu_du.sh "./simpledu" "-l -L test/test-folder/D2"
test/compare_simpledu_du.sh "./simpledu" "-l -L test/test-folder/D1/Db/Dx"
test/compare_simpledu_du.sh "./simpledu" "-l -L test/test-folder"
test/compare_simpledu_du.sh "./simpledu" "-l -L test/test-folder/D1/Db/Dx/symlnk"

test/compare_simpledu_du.sh "./simpledu" "-l -a -L test/test-folder"
test/compare_simpledu_du.sh "./simpledu" "-l -a -L ."
test/compare_simpledu_du.sh "./simpledu" "-l -a -L include"
test/compare_simpledu_du.sh "./simpledu" "-l -a -L acutest"
test/compare_simpledu_du.sh "./simpledu" "-l -a -L test/test-folder/D2"
test/compare_simpledu_du.sh "./simpledu" "-l -a -L test/test-folder/D1/Db/Dx"
test/compare_simpledu_du.sh "./simpledu" "-l -a -L test/test-folder"
test/compare_simpledu_du.sh "./simpledu" "-l -a -L test/test-folder/D1/Db/Dx/symlnk"

test/compare_simpledu_du.sh "./simpledu" "-l --dereference test/test-folder"
test/compare_simpledu_du.sh "./simpledu" "-l --dereference ."
test/compare_simpledu_du.sh "./simpledu" "-l --dereference include"
test/compare_simpledu_du.sh "./simpledu" "-l --dereference acutest"
test/compare_simpledu_du.sh "./simpledu" "-l --dereference test/test-folder/D2"
test/compare_simpledu_du.sh "./simpledu" "-l --dereference test/test-folder/D1/Db/Dx"
test/compare_simpledu_du.sh "./simpledu" "-l --dereference test/test-folder"
test/compare_simpledu_du.sh "./simpledu" "-l --dereference test/test-folder/D1/Db/Dx/symlnk"

test/compare_simpledu_du.sh "./simpledu" "-l -a --dereference test/test-folder"
test/compare_simpledu_du.sh "./simpledu" "-l -a --dereference ."
test/compare_simpledu_du.sh "./simpledu" "-l -a --dereference include"
test/compare_simpledu_du.sh "./simpledu" "-l -a --dereference acutest"
test/compare_simpledu_du.sh "./simpledu" "-l -a --dereference test/test-folder/D2"
test/compare_simpledu_du.sh "./simpledu" "-l -a --dereference test/test-folder/D1/Db/Dx"
test/compare_simpledu_du.sh "./simpledu" "-l -a --dereference test/test-folder"
test/compare_simpledu_du.sh "./simpledu" "-l -a --dereference test/test-folder/D1/Db/Dx/symlnk"

# Testes '-S'
test/compare_simpledu_du.sh "./simpledu" "-l -S test/test-folder"
test/compare_simpledu_du.sh "./simpledu" "-l -S ."
test/compare_simpledu_du.sh "./simpledu" "-l -S include"
test/compare_simpledu_du.sh "./simpledu" "-l -S acutest"
test/compare_simpledu_du.sh "./simpledu" "-l -S -a test/test-folder"
test/compare_simpledu_du.sh "./simpledu" "-l -S -a ."
test/compare_simpledu_du.sh "./simpledu" "-l -S -a include"
test/compare_simpledu_du.sh "./simpledu" "-l -S -a acutest"
test/compare_simpledu_du.sh "./simpledu" "-l -S -a -B 1 test/test-folder"
test/compare_simpledu_du.sh "./simpledu" "-l -S -a -B 1 ."
test/compare_simpledu_du.sh "./simpledu" "-l -S -a -B 1 include"
test/compare_simpledu_du.sh "./simpledu" "-l -S -a -B 1 acutest"
test/compare_simpledu_du.sh "./simpledu" "-l -S -B 10 test/test-folder"
test/compare_simpledu_du.sh "./simpledu" "-l -S -B 10 ."
test/compare_simpledu_du.sh "./simpledu" "-l -S -B 10 include"
test/compare_simpledu_du.sh "./simpledu" "-l -S -B 10 acutest"

test/compare_simpledu_du.sh "./simpledu" "-l --separate-dirs test/test-folder"
test/compare_simpledu_du.sh "./simpledu" "-l --separate-dirs ."
test/compare_simpledu_du.sh "./simpledu" "-l --separate-dirs include"
test/compare_simpledu_du.sh "./simpledu" "-l --separate-dirs acutest"
test/compare_simpledu_du.sh "./simpledu" "-l --separate-dirs -a test/test-folder"
test/compare_simpledu_du.sh "./simpledu" "-l --separate-dirs -a ."
test/compare_simpledu_du.sh "./simpledu" "-l --separate-dirs -a include"
test/compare_simpledu_du.sh "./simpledu" "-l --separate-dirs -a acutest"
test/compare_simpledu_du.sh "./simpledu" "-l --separate-dirs -a -B 1 test/test-folder"
test/compare_simpledu_du.sh "./simpledu" "-l --separate-dirs -a -B 1 ."
test/compare_simpledu_du.sh "./simpledu" "-l --separate-dirs -a -B 1 include"
test/compare_simpledu_du.sh "./simpledu" "-l --separate-dirs -a -B 1 acutest"
test/compare_simpledu_du.sh "./simpledu" "-l --separate-dirs -B 10 test/test-folder"
test/compare_simpledu_du.sh "./simpledu" "-l --separate-dirs -B 10 ."
test/compare_simpledu_du.sh "./simpledu" "-l --separate-dirs -B 10 include"
test/compare_simpledu_du.sh "./simpledu" "-l --separate-dirs -B 10 acutest"


# Testes '--max-depth'
test/compare_simpledu_du.sh "./simpledu" "-l -d 1 test/test-folder"
test/compare_simpledu_du.sh "./simpledu" "-l -d 1 ."
test/compare_simpledu_du.sh "./simpledu" "-l -d 1 include"
test/compare_simpledu_du.sh "./simpledu" "-l -d 1 acutest"
test/compare_simpledu_du.sh "./simpledu" "-l -d 1 -a test/test-folder"
test/compare_simpledu_du.sh "./simpledu" "-l -d 1 -a ."
test/compare_simpledu_du.sh "./simpledu" "-l -d 1 -a include"
test/compare_simpledu_du.sh "./simpledu" "-l -d 1 -a acutest"
test/compare_simpledu_du.sh "./simpledu" "-l -d 1 -a -L test/test-folder"
test/compare_simpledu_du.sh "./simpledu" "-l -d 1 -a -L ."
test/compare_simpledu_du.sh "./simpledu" "-l -d 1 -a -L include"
test/compare_simpledu_du.sh "./simpledu" "-l -d 1 -a -L acutest"

test/compare_simpledu_du.sh "./simpledu" "-l -d 2 test/test-folder"
test/compare_simpledu_du.sh "./simpledu" "-l -d 2 ."
test/compare_simpledu_du.sh "./simpledu" "-l -d 2 include"
test/compare_simpledu_du.sh "./simpledu" "-l -d 2 acutest"
test/compare_simpledu_du.sh "./simpledu" "-l -d 2 -a test/test-folder"
test/compare_simpledu_du.sh "./simpledu" "-l -d 2 -a ."
test/compare_simpledu_du.sh "./simpledu" "-l -d 2 -a include"
test/compare_simpledu_du.sh "./simpledu" "-l -d 2 -a acutest"
test/compare_simpledu_du.sh "./simpledu" "-l -d 2 -a -L test/test-folder"
test/compare_simpledu_du.sh "./simpledu" "-l -d 2 -a -L ."
test/compare_simpledu_du.sh "./simpledu" "-l -d 2 -a -L include"
test/compare_simpledu_du.sh "./simpledu" "-l -d 2 -a -L acutest"

test/compare_simpledu_du.sh "./simpledu" "-l -d 4 test/test-folder"
test/compare_simpledu_du.sh "./simpledu" "-l -d 4 ."
test/compare_simpledu_du.sh "./simpledu" "-l -d 4 include"
test/compare_simpledu_du.sh "./simpledu" "-l -d 4 acutest"
test/compare_simpledu_du.sh "./simpledu" "-l -d 4 -a test/test-folder"
test/compare_simpledu_du.sh "./simpledu" "-l -d 4 -a ."
test/compare_simpledu_du.sh "./simpledu" "-l -d 4 -a include"
test/compare_simpledu_du.sh "./simpledu" "-l -d 4 -a acutest"
test/compare_simpledu_du.sh "./simpledu" "-l -d 4 -a -L test/test-folder"
test/compare_simpledu_du.sh "./simpledu" "-l -d 4 -a -L ."
test/compare_simpledu_du.sh "./simpledu" "-l -d 4 -a -L include"
test/compare_simpledu_du.sh "./simpledu" "-l -d 4 -a -L acutest"

test/compare_simpledu_du.sh "./simpledu" "-l -d 6 test/test-folder"
test/compare_simpledu_du.sh "./simpledu" "-l -d 6 ."
test/compare_simpledu_du.sh "./simpledu" "-l -d 6 include"
test/compare_simpledu_du.sh "./simpledu" "-l -d 6 acutest"
test/compare_simpledu_du.sh "./simpledu" "-l -d 6 -a test/test-folder"
test/compare_simpledu_du.sh "./simpledu" "-l -d 6 -a ."
test/compare_simpledu_du.sh "./simpledu" "-l -d 6 -a include"
test/compare_simpledu_du.sh "./simpledu" "-l -d 6 -a acutest"
test/compare_simpledu_du.sh "./simpledu" "-l -d 6 -a -L test/test-folder"
test/compare_simpledu_du.sh "./simpledu" "-l -d 6 -a -L ."
test/compare_simpledu_du.sh "./simpledu" "-l -d 6 -a -L include"
test/compare_simpledu_du.sh "./simpledu" "-l -d 6 -a -L acutest"

test/compare_simpledu_du.sh "./simpledu" "-l -d 8 test/test-folder"
test/compare_simpledu_du.sh "./simpledu" "-l -d 8 ."
test/compare_simpledu_du.sh "./simpledu" "-l -d 8 include"
test/compare_simpledu_du.sh "./simpledu" "-l -d 8 acutest"
test/compare_simpledu_du.sh "./simpledu" "-l -d 8 -a test/test-folder"
test/compare_simpledu_du.sh "./simpledu" "-l -d 8 -a ."
test/compare_simpledu_du.sh "./simpledu" "-l -d 8 -a include"
test/compare_simpledu_du.sh "./simpledu" "-l -d 8 -a acutest"
test/compare_simpledu_du.sh "./simpledu" "-l -d 8 -a -L test/test-folder"
test/compare_simpledu_du.sh "./simpledu" "-l -d 8 -a -L ."
test/compare_simpledu_du.sh "./simpledu" "-l -d 8 -a -L include"
test/compare_simpledu_du.sh "./simpledu" "-l -d 8 -a -L acutest"

test/compare_simpledu_du.sh "./simpledu" "-l --max-depth=1 test/test-folder"
test/compare_simpledu_du.sh "./simpledu" "-l --max-depth=1 ."
test/compare_simpledu_du.sh "./simpledu" "-l --max-depth=1 include"
test/compare_simpledu_du.sh "./simpledu" "-l --max-depth=1 acutest"
test/compare_simpledu_du.sh "./simpledu" "-l --max-depth=1 -a test/test-folder"
test/compare_simpledu_du.sh "./simpledu" "-l --max-depth=1 -a ."
test/compare_simpledu_du.sh "./simpledu" "-l --max-depth=1 -a include"
test/compare_simpledu_du.sh "./simpledu" "-l --max-depth=1 -a acutest"
test/compare_simpledu_du.sh "./simpledu" "-l --max-depth=1 -a -L test/test-folder"
test/compare_simpledu_du.sh "./simpledu" "-l --max-depth=1 -a -L ."
test/compare_simpledu_du.sh "./simpledu" "-l --max-depth=1 -a -L include"
test/compare_simpledu_du.sh "./simpledu" "-l --max-depth=1 -a -L acutest"
test/compare_simpledu_du.sh "./simpledu" "-l --max-depth=2 test/test-folder"
test/compare_simpledu_du.sh "./simpledu" "-l --max-depth=2 ."
test/compare_simpledu_du.sh "./simpledu" "-l --max-depth=2 include"
test/compare_simpledu_du.sh "./simpledu" "-l --max-depth=2 acutest"
test/compare_simpledu_du.sh "./simpledu" "-l --max-depth=2 -a test/test-folder"
test/compare_simpledu_du.sh "./simpledu" "-l --max-depth=2 -a ."
test/compare_simpledu_du.sh "./simpledu" "-l --max-depth=2 -a include"
test/compare_simpledu_du.sh "./simpledu" "-l --max-depth=2 -a acutest"
test/compare_simpledu_du.sh "./simpledu" "-l --max-depth=2 -a -L test/test-folder"
test/compare_simpledu_du.sh "./simpledu" "-l --max-depth=2 -a -L ."
test/compare_simpledu_du.sh "./simpledu" "-l --max-depth=2 -a -L include"
test/compare_simpledu_du.sh "./simpledu" "-l --max-depth=2 -a -L acutest"
test/compare_simpledu_du.sh "./simpledu" "-l --max-depth=4 test/test-folder"
test/compare_simpledu_du.sh "./simpledu" "-l --max-depth=4 ."
test/compare_simpledu_du.sh "./simpledu" "-l --max-depth=4 include"
test/compare_simpledu_du.sh "./simpledu" "-l --max-depth=4 acutest"
test/compare_simpledu_du.sh "./simpledu" "-l --max-depth=4 -a test/test-folder"
test/compare_simpledu_du.sh "./simpledu" "-l --max-depth=4 -a ."
test/compare_simpledu_du.sh "./simpledu" "-l --max-depth=4 -a include"
test/compare_simpledu_du.sh "./simpledu" "-l --max-depth=4 -a acutest"
test/compare_simpledu_du.sh "./simpledu" "-l --max-depth=4 -a -L test/test-folder"
test/compare_simpledu_du.sh "./simpledu" "-l --max-depth=4 -a -L ."
test/compare_simpledu_du.sh "./simpledu" "-l --max-depth=4 -a -L include"
test/compare_simpledu_du.sh "./simpledu" "-l --max-depth=4 -a -L acutest"
test/compare_simpledu_du.sh "./simpledu" "-l --max-depth=6 test/test-folder"
test/compare_simpledu_du.sh "./simpledu" "-l --max-depth=6 ."
test/compare_simpledu_du.sh "./simpledu" "-l --max-depth=6 include"
test/compare_simpledu_du.sh "./simpledu" "-l --max-depth=6 acutest"
test/compare_simpledu_du.sh "./simpledu" "-l --max-depth=6 -a test/test-folder"
test/compare_simpledu_du.sh "./simpledu" "-l --max-depth=6 -a ."
test/compare_simpledu_du.sh "./simpledu" "-l --max-depth=6 -a include"
test/compare_simpledu_du.sh "./simpledu" "-l --max-depth=6 -a acutest"
test/compare_simpledu_du.sh "./simpledu" "-l --max-depth=6 -a -L test/test-folder"
test/compare_simpledu_du.sh "./simpledu" "-l --max-depth=6 -a -L ."
test/compare_simpledu_du.sh "./simpledu" "-l --max-depth=6 -a -L include"
test/compare_simpledu_du.sh "./simpledu" "-l --max-depth=6 -a -L acutest"
test/compare_simpledu_du.sh "./simpledu" "-l --max-depth=8 test/test-folder"
test/compare_simpledu_du.sh "./simpledu" "-l --max-depth=8 ."
test/compare_simpledu_du.sh "./simpledu" "-l --max-depth=8 include"
test/compare_simpledu_du.sh "./simpledu" "-l --max-depth=8 acutest"
test/compare_simpledu_du.sh "./simpledu" "-l --max-depth=8 -a test/test-folder"
test/compare_simpledu_du.sh "./simpledu" "-l --max-depth=8 -a ."
test/compare_simpledu_du.sh "./simpledu" "-l --max-depth=8 -a include"
test/compare_simpledu_du.sh "./simpledu" "-l --max-depth=8 -a acutest"
test/compare_simpledu_du.sh "./simpledu" "-l --max-depth=8 -a -L test/test-folder"
test/compare_simpledu_du.sh "./simpledu" "-l --max-depth=8 -a -L ."
test/compare_simpledu_du.sh "./simpledu" "-l --max-depth=8 -a -L include"
test/compare_simpledu_du.sh "./simpledu" "-l --max-depth=8 -a -L acutest"

# Testes com vários
test/compare_simpledu_du.sh "./simpledu" "-l -S -B 10 acutest include test"

# Testes com barra final
test/compare_simpledu_du.sh "./simpledu" "-l -a test/test-folder/"
test/compare_simpledu_du.sh "./simpledu" "-l -a ./"
test/compare_simpledu_du.sh "./simpledu" "-l -a include/"
test/compare_simpledu_du.sh "./simpledu" "-l -a acutest/"

# Testes com erro
test/compare_simpledu_du.sh "./simpledu" "-l a"
test/compare_simpledu_du.sh "./simpledu" "-l a include"
test/compare_simpledu_du.sh "./simpledu" "-l a include acutest"
test/compare_simpledu_du.sh "./simpledu" "-l include a acutest"
test/compare_simpledu_du.sh "./simpledu" "-l include acutest a"
test/compare_simpledu_du.sh "./simpledu" "-l a b"
test/compare_simpledu_du.sh "./simpledu" "-l b a"
test/compare_simpledu_du.sh "./simpledu" "-l include b acutest a test"
test/compare_simpledu_du.sh "./simpledu" "-e"
test/compare_simpledu_du.sh "./simpledu" "-eij"
test/compare_simpledu_du.sh "./simpledu" "-jie"
test/compare_simpledu_du_out.sh "./simpledu" "--eij"
test/compare_simpledu_du_out.sh "./simpledu" "--jie"
test/compare_simpledu_du.sh "./simpledu" "include -e"
test/compare_simpledu_du.sh "./simpledu" "-eij ."
test/compare_simpledu_du.sh "./simpledu" "-jie a"

# Testes de outros sítios
curr_dir=${PWD##*/}
cd ..
$curr_dir/test/compare_simpledu_du.sh "$curr_dir/simpledu" "-l -a $curr_dir/test/test-folder/"
$curr_dir/test/compare_simpledu_du.sh "$curr_dir/simpledu" "-l -a $curr_dir/"
$curr_dir/test/compare_simpledu_du.sh "$curr_dir/simpledu" "-l -a $curr_dir/include/"
$curr_dir/test/compare_simpledu_du.sh "$curr_dir/simpledu" "-l -a $curr_dir/acutest/"
cd $curr_dir

# Testes para ficheiros e para symlinks que apontam para ficheiros
test/compare_simpledu_du.sh "./simpledu" "-l include/simpledu_args.h"
test/compare_simpledu_du.sh "./simpledu" "-l test/test-folder/D1/Db/Dx/F3bin -a"
test/compare_simpledu_du.sh "./simpledu" "-l test/test-folder/D1/Db/Dx/F3bin -a -L"

# Testes grandes
test/compare_simpledu_du.sh "./simpledu" "-l .."
test/compare_simpledu_du.sh "./simpledu" "-l ../../.docker"
test/compare_simpledu_du.sh "./simpledu" "-l ../.."
test/compare_simpledu_du.sh "./simpledu" "-l ../../.."
test/compare_simpledu_du.sh "./simpledu" "-l /home"
